# Generated by Django 5.2.3 on 2025-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
